<a href="https://colab.research.google.com/github/RahulJuluru2/NotesForReference/blob/main/PYTORCH_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# tensor can be any representation of number
# fundamental component of pytorch
# input > numerical encoding >> learn representation ( patterns / features / weights) > representation outputs > outputs

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.0+cu113


In [3]:
!nvidia-smi

Tue Aug  9 04:02:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to tensors

### Creating tensors
## Pytorch tensors are created using 'torch.tensor()'

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector = 
# Size = # of pairs of closing square brackets
# Shape = # of elements
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
## Tensor
TENSOR = torch.tensor([[
                  [1,3,4],
                  [4,5,6],
                  [7,8,9]]])
TENSOR

tensor([[[1, 3, 4],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 3, 4],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
TENSOR = torch.tensor([
                        [
                          [1,3,4],
                          [4,5,6]
                        ]
                      ])
TENSOR

tensor([[[1, 3, 4],
         [4, 5, 6]]])

In [20]:
TENSOR.shape

torch.Size([1, 2, 3])

### Random tensors

In [21]:
## Why random tensors ?

## Random tensors are important because the way many NN learn is that they start with tensors full of random num bers and then adjust those random numbers to better represent the data
## Start with random numbers > look at data > update random numbers > look at data >> update random numbers

In [22]:
# Create a random tensor of size 3 ,4 
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9221, 0.5232, 0.9966, 0.9854],
        [0.2419, 0.7628, 0.7458, 0.2519],
        [0.8820, 0.5057, 0.7941, 0.4860]])

In [23]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # h ,w ,c 
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [27]:
# Use torch.range()
torch.range(0,10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
one_to_eleven = torch.arange(start = 1, end = 50 , step = 5)
one_to_eleven

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [29]:
# Creating tensors like 
ten_zeros = torch.zeros_like(input=one_to_eleven)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data types

In [30]:
# Float 32 tensor

## Tensor datatypes is one of the the 3 big issues that you will run into with pytorch & deep learning
# 1. Tensors not right datatype - to do get datatype of tensor some_tensor.dtype
# 2. Tensors not right shape - to get shape of tensor : some_tensor.shape
# 3. Tensors not on right device
float_32_tensor = torch.tensor([3,6,9],dtype = None)
float_32_tensor

tensor([3, 6, 9])

In [31]:
float_32_tensor.dtype

torch.int64

In [32]:
float_16_tnsor = torch.tensor([3,6,9] , 
                              dtype = None, # data type of tensor (eg, float16 or float32 or float64)
                              device = "cuda", # What devi ce is your tensor on 
                              requires_grad = False ) # whether or not to track gradients

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [35]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

## Manipulating tensors (tensor operations)

In [36]:
# tensor operations include : + , - , * , / 
# matrix multiplication

In [37]:
# Create a tensor and add 100 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [38]:
# multiply tensor by 8
tensor * 8

tensor([ 8, 16, 24])

In [39]:
# subtract 
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Try out pytorch inbuilt functions 
torch.mul(tensor,10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor,10)


tensor([11, 12, 13])

## Matrix multuplication 

## Two main ways of performing multiplication in NN and deep learning:
# 1. Element-wise multiplication
# 2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
       * (3 ,2 ) @ (3,2) = won't work
       * (2 ,3 ) @ (3,2) = will work
2. the resulting matrix has the shape of the **outer dimension**:
      * (2 ,3 ) @ (3,2) = (2,2) is the size of resulting matrix

In [42]:
# Element wise multiplication
print(tensor  , "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [43]:
# Matrix multiplicaiton
torch.matmul(tensor,tensor)

tensor(14)

In [44]:
# MAtrix multiplicaiton by hand
1*1 + 2*2 + 3*3

14

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 9.54 ms, sys: 0 ns, total: 9.54 ms
Wall time: 11.4 ms


In [46]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 49 µs, sys: 0 ns, total: 49 µs
Wall time: 52.9 µs


tensor(14)

In [47]:
## one of the most common problems in deep learning:shape errors

In [48]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

# torch.matmul(tensor_A,tensor_B)

In [49]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix the tensor shape issues , we can manipulate the shape of one of our tensors using a **transpose** .
A **transpose** switches the axes or dimensions of a given vector


In [50]:
tensor_A.T , tensor_A.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]), torch.Size([2, 3]))

In [51]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

## Finding the min,max,mean,sum etc ( tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [54]:
# find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [55]:
# FInd the mean - note: the 
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

# Find the positional min and max in tensor


In [57]:
torch.argmin(x) , torch.argmax(x)

(tensor(0), tensor(9))

In [58]:
x.argmin() , x.argmax()

(tensor(0), tensor(9))

In [59]:
x[0]

tensor(0)

In [60]:
x[9]

tensor(90)

## Reshaping , stacking , squeezing , unsqueezing tensors

In [61]:
 # * reshaping - reshapes an input tensor to a defined shape
 # * view - Return a view of input tensor of certain shape but keep the same memory as the original tensor
 # * stacking - combine multiple tensor on top of each other (vstack) or side by side(hstack)
 # * squeeze - removes all '1' dimensions from a tensor
 # * unsqueeze - adds '1' dimensions to a tensor
 # * permute - returnsa view of the input with dimensions permuted(swapped) in a certain way

In [62]:
#Lets create a tensor 
import torch
x = torch.arange(1. , 11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [63]:
x_reshaped = x.reshape(5,2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [64]:
# Change the view
z = x.view(1,10)
z , z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [65]:
# Changing z changes x (because a view of the tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x],dim=0)
x_stacked , x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([3, 10]))

In [67]:
# torch.squeeze - removes all '1' dimensions 
x = torch.squeeze(x)
x

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [68]:
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")

Previous tensor:tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
Previous shape:torch.Size([5, 2])


In [69]:
x_squeezed = x_reshaped.squeeze()
print(f"New tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

New tensor:tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
New shape:torch.Size([5, 2])


In [70]:
# Add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")


New tensor:tensor([[[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]])
New shape:torch.Size([1, 5, 2])


In [71]:
# torch.permute - rearranges the dim of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[ht,width,color_channels]

# Permute
x_permuted = x_original.permute(2,0,1) # shifts axes 0 > 1 , 1 >2 , 2 >0
print(f"before shape: {x_original.shape}")
print(f"after shape: {x_permuted.shape}")

before shape: torch.Size([224, 224, 3])
after shape: torch.Size([3, 224, 224])


# Selecting data from tensors
## Indexing (selecting data from tensors)

In [72]:
# Create a tensor
import torch

In [73]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [74]:
# Lets index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
# lets index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [76]:
# Lets index on most inner bracket
x[0][0][0]

tensor(1)

# pyTorch tensors and numpy

Numpy is a popular scientific python numerical computing library
and because of this , pytorch has functionality to interact with it
* numpy > pytorch tensor >> torch.from_numpy(ndarray)
* Pytorch tensor > numpy >> tensor.numpy()

In [77]:
import torch
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array) # warning : from converting numpy to pytorch , pytorch reflects numpy's default
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
tensor.dtype

torch.float64

In [79]:
# Change the value of array , what will this do to 'tensor' ? No changes
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [80]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Running tensors and Pytorch objects on GPU (making faster computations)

GPUs = faster ocmputation on numbers ,thanks to CUDA + NVIDIA +Pytorch working behind the scenes to make everything hunky dory


In [81]:
import torch

## 1. Getting a GPU 
### 1. Easiest = Google colab for free and upgrade
### 2. use your own GPU = Take a liitle bit of setup and requires investments
### 3. use cloud computing - GCP , AWS , Azure , these services allow you to rent computers on the cloud and access them

#### For 2,3 Pytorch+ GPU drivers (CUDA) takes a little bit of setting up,to do this, refer to pytorch setup documentation

In [85]:
!nvidia-smi

Tue Aug  9 04:04:24 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    27W /  70W |    610MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Check for GPU access with pytorch

In [86]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [87]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [88]:
# Count number of GPU
torch.cuda.device_count()

1

In [ ]:
## 3. Putting tensors and models on GPU
# The reason we want our tensors / models on GPU is beacuse using a GPU results in faster computation

In [90]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1,2,3],device="cpu")
tensor , tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [91]:
# Move to GPU if its available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
### Numpy works only on CPU 
## Moving tensors back to CPU
## IF tensor is on GPU , cant transform on Numpy

In [95]:
# To fix the GPU to CPU and then convert to numpy array
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])